#!/usr/bin/env node
/**
 * Generates .storybook/generated/storyMap.ts — a static require() map for all
 * stories in packages/components.
 *
 * Why: Metro (0.84+, Expo SDK 57) cannot collapse require.context() directories
 * that live outside the app projectRoot ("Failed to collapse"). A generated
 * map of literal requires gives Metro static analysability and gives Storybook
 * the same req.keys()/req() interface as require.context.
 */
const fs = require('fs');
const path = require('path');

const appDir = path.resolve(__dirname, '..');
const componentsDir = path.resolve(appDir, '../../packages/components');
const outDir = path.join(appDir, '.storybook/generated');
const outFile = path.join(outDir, 'storyMap.ts');

function walk(dir, acc = []) {
  for (const entry of fs.readdirSync(dir, { withFileTypes: true })) {
    const p = path.join(dir, entry.name);
    if (entry.isDirectory()) {
      if (entry.name === 'node_modules' || entry.name === 'dist') continue;
      walk(p, acc);
    } else if (/\.stories\.(ts|tsx|js|jsx)$/.test(entry.name)) {
      acc.push(p);
    }
  }
  return acc;
}

const stories = walk(componentsDir).sort();

const lines = stories.map((abs) => {
  // Key relative to packages/components — must match the storybook entry's
  // `directory` semantics ('./atoms/.../X.stories')
  const key = './' + path.relative(componentsDir, abs).replace(/\\/g, '/');
  // require path relative to .storybook/generated/
  const reqPath = path.relative(outDir, abs).replace(/\\/g, '/');
  return `  ${JSON.stringify(key)}: () => require(${JSON.stringify(reqPath)}),`;
});

const content = `/* AUTO-GENERATED by scripts/gen-stories.cjs — do not edit. */
/* eslint-disable */
// @ts-nocheck

const modules: Record<string, () => unknown> = {
${lines.join('\n')}
};

export default modules;
`;

fs.mkdirSync(outDir, { recursive: true });
fs.writeFileSync(outFile, content);
console.log(`✅ storyMap: ${stories.length} stories → ${path.relative(appDir, outFile)}`);
